[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdts = "7.3.0"
rand = "0.8.5"
uuid = { version = "1.3.0", features = [ "v4", "fast-rng" ] }
