[package]
name = "gossip-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
gossip = { path = "../gossip" }
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "1.3.0", features = [ "v4" ] }
serde-wasm-bindgen = "0.5.0"
